export const PERMISSIONS = {
  dashboardView: 'dashboard:view',
  usersManage: 'users:manage',
  rolesManage: 'roles:manage',
  settingsManage: 'settings:manage',
  propertiesManage: 'properties:manage',
  unitsManage: 'units:manage',
  landlordsManage: 'landlords:manage',
  tenantsManage: 'tenants:manage',
  tenanciesManage: 'tenancies:manage',
  chargesManage: 'charges:manage',
  paymentsRecord: 'payments:record',
  paymentsReverse: 'payments:reverse',
  paymentsReconcile: 'payments:reconcile',
  receiptsView: 'receipts:view',
  penaltiesManage: 'penalties:manage',
  penaltiesWaive: 'penalties:waive',
  depositsManage: 'deposits:manage',
  utilitiesManage: 'utilities:manage',
  repairsManage: 'repairs:manage',
  repairDeductionsApprove: 'repair-deductions:approve',
  statementsGenerate: 'statements:generate',
  payoutsManage: 'payouts:manage',
  payoutsMarkPaid: 'payouts:mark-paid',
  inquiriesManage: 'inquiries:manage',
  reportsView: 'reports:view',
  websiteManage: 'website:manage',
  auditView: 'audit:view',
  offlineSyncResolve: 'offline-sync:resolve',
  ownTenantPortalView: 'tenant-portal:own:view',
  ownLandlordPortalView: 'landlord-portal:own:view',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSION_MATRIX: Record<string, PermissionCode[]> = {
  admin: Object.values(PERMISSIONS),
  staff: [
    PERMISSIONS.dashboardView,
    PERMISSIONS.propertiesManage,
    PERMISSIONS.unitsManage,
    PERMISSIONS.tenantsManage,
    PERMISSIONS.tenanciesManage,
    PERMISSIONS.chargesManage,
    PERMISSIONS.paymentsRecord,
    PERMISSIONS.paymentsReconcile,
    PERMISSIONS.receiptsView,
    PERMISSIONS.repairsManage,
    PERMISSIONS.inquiriesManage,
    PERMISSIONS.reportsView,
  ],
  tenant: [PERMISSIONS.ownTenantPortalView, PERMISSIONS.receiptsView],
  landlord: [PERMISSIONS.ownLandlordPortalView],
};
